# Create a minimal container to run a Golang static binary
FROM scratch

COPY ranchhand.yml /ranchhand.yml

ADD ca-certificates.crt /etc/ssl/certs/
ADD awsranchhand /

ENTRYPOINT ["./awsranchhand"]
CMD ["--help"]
